version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./client:/app  # For development (remove in production)
      - /app/node_modules